version: 2.1
orbs:
  go: circleci/go@1.7.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # working_directory: ${WORKSPACE}/test-app
    docker:
      # replace with your preferred image
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: "build go binary"
          # command: "cd test-app ; ls -all & pwd & CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/ops-test-app"
          command: "CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/ops-test-app"
          working_directory: ./test-app
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      # replace with your preferred image
      - image: cimg/go:1.17
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: run docker version"
          command: "ls -all; docker version"
          working_directory: ./test-app
      # build and push Docker image
      - run:
          name: "docker image build"
          command: "ls -all ; sh build.sh docker_image_build"
          working_directory: ./test-app
      - run:
          name: "netstat -tulpn"
          command: "netstat -tulpn ; docker ps"
          working_directory: ./test-app
      - run:
          name: "test docker image"
          command: "sh build.sh test_package"
          working_directory: ./test-app
      - persist_to_workspace:
          root: .
          paths:
            - .
  push:
    docker:
      # replace with your preferred image
      - image: cimg/go:1.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "docker image build"
          command: "sh build.sh docker_image_push"
          working_directory: ./test-app
        #working_directory: ./test-app
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test