version: "3.2"

services:
  faceit:
    image: anatolman/${APP_NAME}:${TAG}
    container_name: ${APP_NAME}
    network_mode: host
    build:
      context: .
      args:
        VERSION: ${TAG}
    environment:
    - POSTGRESQL_HOST=localhost
    - POSTGRESQL_PORT=5432
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASSWORD=mysecretpassword
    - POSTGRESQL_DBNAME=postgres
    ports:
      - '8080:8080'
  postgres:
    image: postgres:13-alpine
    container_name: postrgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    network_mode: host
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    # volumes: 
    #   - ./postgres-data:/var/lib/postgresql/data
    #   # copy the sql script to create tables
    #   - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
